In [2]:
import numpy as np

array = [[1,2,3],[4,5,6]]
np_array = np.array(array)
print("Array type: {}".format(type(np_array)))
print("Array shape: {}".format(np.shape(np_array)))
print(np_array)

Array type: <class 'numpy.ndarray'>
Array shape: (2, 3)
[[1 2 3]
 [4 5 6]]


In [4]:
import torch
tensor = torch.Tensor(array)
print("Array type: {}".format(tensor.type))
print("Array shape: {}".format(tensor.shape))
print(tensor)

Array type: <built-in method type of Tensor object at 0x000001FF87437950>
Array shape: torch.Size([2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [8]:
print("Numpy {}\n".format(np.ones((2,3))))
print(torch.ones(2,3))

Numpy [[1. 1. 1.]
 [1. 1. 1.]]

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [12]:
print("Numpy {}\n".format(np.random.rand(2,3)))
print(torch.rand(2,3))

Numpy [[0.88298376 0.42326047 0.41229359]
 [0.78314516 0.39356354 0.2658303 ]]

tensor([[0.9180, 0.8215, 0.4707],
        [0.8505, 0.7009, 0.5331]])


In [13]:
array = np.random.rand(2,3)
print("{} {}\n".format(type(array), array))
from_numpy_to_tensor = torch.from_numpy(array)
tensor = from_numpy_to_tensor
print("{}\n".format(tensor))
from_tensor_to_numpy = tensor.numpy()
print("{} {}\n".format(type(from_tensor_to_numpy), from_tensor_to_numpy))

<class 'numpy.ndarray'> [[0.05847128 0.9509499  0.30015439]
 [0.37369053 0.24287266 0.15510412]]

tensor([[0.0585, 0.9509, 0.3002],
        [0.3737, 0.2429, 0.1551]], dtype=torch.float64)

<class 'numpy.ndarray'> [[0.05847128 0.9509499  0.30015439]
 [0.37369053 0.24287266 0.15510412]]



In [19]:
tensor = torch.ones(3,3)
print("\n", tensor)

print("{}{}\n".format(tensor.view(9).shape, tensor.view(9)))

print("Addition: {}\n".format(torch.add(tensor,tensor)))

print("Subtraction: {}\n".format(tensor.sub(tensor)))

print("Multiplication: {}\n".format(tensor.mul(tensor)))

print("Division: {}".format(tensor.div(tensor)))

tensor = torch.Tensor([1,2,3,4,5])

print("Mean: {}\n".format(tensor.mean()))

print("Std: {}".format(tensor.std()))


 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.Size([9])tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.])

Addition: tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

Subtraction: tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Multiplication: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

Division: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
Mean: 3.0

Std: 1.5811388492584229


In [22]:
from torch.autograd import Variable

var = Variable(torch.ones(3), requires_grad = True)
var

tensor([1., 1., 1.], requires_grad=True)

In [26]:
array = [2,4]
tensor = torch.Tensor(array)
x = Variable(tensor, requires_grad = True)
y = x**2
print("y= ",y)
o = 1/2*sum(y)
print("o= ",o)
o.backward()
print("gradiants: ",x.grad)


y=  tensor([ 4., 16.], grad_fn=<PowBackward0>)
o=  tensor(10., grad_fn=<MulBackward0>)
gradiants:  tensor([2., 4.])


In [28]:
x = torch.tensor(3.0, requires_grad=True)
y = x**2 + 2*x
print(y.grad_fn) 

print(y.grad_fn.next_functions)

((<PowBackward0 object at 0x000001FF88002710>, 0), (<MulBackward0 object at 0x000001FF88001F60>, 0))
