In [2]:
import numpy as np

array = [[1,2,3],[4,5,6]]
np_array = np.array(array)
print("Array type: {}".format(type(np_array)))
print("Array shape: {}".format(np.shape(np_array)))
print(np_array)

Array type: <class 'numpy.ndarray'>
Array shape: (2, 3)
[[1 2 3]
 [4 5 6]]


In [4]:
import torch
tensor = torch.Tensor(array)
print("Array type: {}".format(tensor.type))
print("Array shape: {}".format(tensor.shape))
print(tensor)

Array type: <built-in method type of Tensor object at 0x000001FF87437950>
Array shape: torch.Size([2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [8]:
print("Numpy {}\n".format(np.ones((2,3))))
print(torch.ones(2,3))

Numpy [[1. 1. 1.]
 [1. 1. 1.]]

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [12]:
print("Numpy {}\n".format(np.random.rand(2,3)))
print(torch.rand(2,3))

Numpy [[0.88298376 0.42326047 0.41229359]
 [0.78314516 0.39356354 0.2658303 ]]

tensor([[0.9180, 0.8215, 0.4707],
        [0.8505, 0.7009, 0.5331]])


In [13]:
array = np.random.rand(2,3)
print("{} {}\n".format(type(array), array))
from_numpy_to_tensor = torch.from_numpy(array)
tensor = from_numpy_to_tensor
print("{}\n".format(tensor))
from_tensor_to_numpy = tensor.numpy()
print("{} {}\n".format(type(from_tensor_to_numpy), from_tensor_to_numpy))

<class 'numpy.ndarray'> [[0.05847128 0.9509499  0.30015439]
 [0.37369053 0.24287266 0.15510412]]

tensor([[0.0585, 0.9509, 0.3002],
        [0.3737, 0.2429, 0.1551]], dtype=torch.float64)

<class 'numpy.ndarray'> [[0.05847128 0.9509499  0.30015439]
 [0.37369053 0.24287266 0.15510412]]

